### ISSUE TITLE
ModuleNotFoundError: pyfade not found

### ISSUE THREAD

**Issue by zly-dev** [Its-Vichy/Zapp#1]
i edited the token and message into the code, and when running on repl and in terminal, get this error

also, for the message, are the three ` neccessary?

**Comment by Its-Vichy** [comment]
pip install pyfade ._.

**Comment by zly-dev** [comment]
look this comes from repl: https://cccccccccccccccccccccccccccccccccccccccccccccccccccccccccc.cc/TO2Tu1aR

and on terminal i get a super long error
